sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: F+g2Atr0hl1+RigTICUUD6deoa4JRIRfyMu5HfMf4aozI4I7N7bvaSDHdZkYF5a2aKpOxJopkwUVRW95OlnKlyCcS9Z+859DaYDMQK/kOyeQ1enXNN0abgb+QcpXudnvqXRT5owR5GR1Kbmm1H1HoX3aIRBCMEibVOPlRGHCrRIQkAG7YZNAR63fWT9FLBhOFPUy6wDainH/tuALrxbZ781lFm6VvA6ixCur74+jQJz1+7rfMnKi6m+ljLcNSma97FoWiuQKuIhOCDuY12dn49Hp12IjoQ+l0mKLh8+W0X5uHFmKac550JN1o4PKuej0PsUiKfiWhUVnf2QoebjvxrPH1JHchpVEUIbcNEHU4HUVgSOaH3qiL/dWM9WRt7IMeBSDv7e4YhqM1H0K9G7mKIV6t1ySpnkTzmYWEWWp90P24YjNN0n5GYll2mzikGuCy/4HOPd0zvlAqIxkbZiZwj6mJRkJexs77QdTX6HypOFAYFCcrJIImEfSZTlJCFIGOM8dfoMV0W9WTLtDBidFpbR+5PAR1XVqTQ+sAehn80gySb2796Kv1//w/WEgwOOPl+OH6bnpZH61vkLMTTp7N3eCzis6kGsy5nf4HwFhzeGXLjvtyqgFGnEzhGPSkbOCh96SHIjS0VE8phPAJ0O8nJBDKcxyRgGbBDzpqXAD5Ok=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Diary-of-Samuel-Pepys---Complete-1660-N.S._4125
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy